services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10

  spring-app:
    build: .
    container_name: spring-boot-container
    ports:
      - "8080:8080"
    depends_on:
      mysql-db:
        condition: service_healthy
    env_file:
      - .env

volumes:
  mysql_data: