### Get all users
GET http://localhost:8080/api/v1/users?page=0&size=10&sortBy=name&sortDirection=DESC
Content-Type: application/json

### Get all user details
GET http://localhost:8080/api/v1/users/1
Content-Type: application/json

### Test POST request
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
    "name": "Kulani",
    "role": "Developer",
    "email":"rhandzu@yahoo.com"
}


### Test Post request
POST http://localhost:8080/api/v1/accounts/user/11
Content-Type: application/json
Accept: application/json

{
    "accountType": "FIXED"
}


### Test Post request
POST http://localhost:8080/api/v1/accounts/user/1?accountNumber=12345&accountType=SAVINGS


### Retrieve the account you just created
GET http://localhost:8080/api/v1/accounts/1

### Retrieve the account you just created
GET http://localhost:8080/api/v1/accounts

### Test Deposit
POST http://localhost:8080/api/v1/accounts/1/deposit
Content-Type: application/json
Accept: application/json
Idempotency-Key: 7b9b1e5a-2b3c-4d5e-af6g-kkkk1

{
    "amount": 500
}


### Test Withdraw
POST http://localhost:8080/api/v1/accounts/1/withdraw
Content-Type: application/json
Accept: application/json
Idempotency-Key: 7b9b1e5a-2b3c-4d5e-af6g-eddw

{
    "amount": 100
}

### Test tranfer
POST http://localhost:8080/api/v1/accounts/2/transfer
Content-Type: application/json
Accept: application/json
Idempotency-Key: 7b9b1e5a-2b3c-4d5e-af6g-ouuuttt

{
  "targetAccountId": 3,
  "amount": 100
}

### get statement
GET http://localhost:8080/api/accounts/statement/2

